package com.senthil.presto.coding.dao;

import com.senthil.presto.coding.beans.Item;
import com.senthil.presto.coding.beans.Menu;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;

public class H2MenuDao {

    private Logger logger = LoggerFactory.getLogger(H2MenuDao.class.getName());
    private String INSERT_MENU = "INSERT INTO Menu (RESTAURANT_ID, NAME, MENU_TYPE) values (?, ?, ?)";
    private String INSERT_MENU_ITEM = "INSERT INTO Item (MENU_ID, NAME, MODIFIER, PARENT_ID) values (?, ?, ?, ?)";

    public Menu getMenu(int id, String type) {

        return new Menu();
    }

    public void executeStatement(String sql) throws Exception{
        Statement statement = getConnection().createStatement();
        statement.execute(sql);
    }

    public int insertMenu(Menu menu) throws Exception {
        PreparedStatement ps = getConnection().prepareStatement(INSERT_MENU, Statement.RETURN_GENERATED_KEYS);
        ps.setInt(1, menu.getRestaurantId());
        ps.setString(2, menu.getName());
        ps.setString(3, menu.getMenuType().name());
        ps.executeUpdate();

        ResultSet tableKeys = ps.getGeneratedKeys();
        tableKeys.next();
        int autoGeneratedID = tableKeys.getInt(1);
        return autoGeneratedID;
    }

    public void insertMenuItem(Item root, int menuId, int parentId) throws Exception {
        PreparedStatement ps = getConnection().prepareStatement(INSERT_MENU_ITEM, Statement.RETURN_GENERATED_KEYS);
        ps.setInt(1, menuId);
        ps.setString(2, root.getName());
        ps.setString(3, root.isModifier()? "Y": "N");
        ps.setInt(4, parentId);
        ps.executeUpdate();

        ResultSet tableKeys = ps.getGeneratedKeys();
        tableKeys.next();
        int autoGeneratedID = tableKeys.getInt(1);
        logger.info("Inserted the item# {}", autoGeneratedID);

        List<Item> items = root.getModifiers();

        //Recursively call the menu item insertion
        if (items != null && items.size() > 0) {
            for (Item item : items) insertMenuItem(item, menuId, autoGeneratedID);
        }
    }

    Connection getConnection() {
        Connection conn = null;
        try {
            Class.forName("org.h2.Driver");
            conn = DriverManager.getConnection("jdbc:h2:tcp://127.0.1.1:9092/~/menu", "sa", "");
            logger .info("Connection Established: "+ conn.getMetaData().getDatabaseProductName() + "/" + conn.getCatalog());
        } catch (Exception e) {
            logger.error(e.getMessage());
            e.printStackTrace();
        }
        return conn;
    }
}
